name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    env:
      NPM_ACCESS_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        env:
          NPM_ACCESS_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
      - run: npm test
        env:
          NPM_ACCESS_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
